export const GET_ERRORS = "GET_ERRORS";
export const GET_PROJECTS = "GET_PROJECTS";
export const GET_PROJECT = "GET_PROJECT";
export const GET_SAVEDPROJECT = "GET_SAVEDPROJECT";
export const SHOW_DELETED_PROJECTS = "SHOW_DELETED_PROJECTS";
export const REMOVE_PROJECT = "REMOVE_PROJECT";
export const SHOW_PROJECTS_EXCLUDE_IDENTIFIER =
  "SHOW_PROJECTS_EXCLUDE_IDENTIFIER";
export const EMPTY_OUT_PROJECTS = "EMPTY_OUT_PROJECTS";

//Types for BACKLOG ACTIONS:
export const GET_BACKLOG = "GET_BACKLOG";
export const GET_PROJECT_ID = "GET_PROJECT_ID";
export const GET_PROJECT_NAME = "GET_PROJECT_NAME";
export const GET_PROJECT_TASK = "GET_PROJECT_TASK";
export const DELETE_PROJECT_TASK = "DELETE_PROJECT_TASK";
export const SAVE_PROJECT_TASK = "SAVE_PROJECT_TASK";
export const GET_SAVED_PROJECT_TASK = "GET_SAVED_PROJECT_TASK";
export const EMPTY_OUT_PTS = "EMPTY_OUT_PTS";
export const SHOW_PT_EXCLUDE_IDENTIFIER = "SHOW_PT_EXCLUDE_IDENTIFIER";
