export const GET_ERRORS = "GET_ERRORS";
export const GET_PROJECTS = "GET_PROJECTS";
export const GET_PROJECT = "GET_PROJECT";
export const GET_SAVEDPROJECT = "GET_SAVEDPROJECT";
export const SHOW_DELETED_PROJECTS = "SHOW_DELETED_PROJECTS";
export const REMOVE_PROJECT = "REMOVE_PROJECT";
export const SHOW_PROJECTS_EXCLUDE_IDENTIFIER =
  "SHOW_PROJECTS_EXCLUDE_IDENTIFIER";
